#!/bin/tcsh

cat > Input <<endofdata1
Ncycle   Ninit   Npart   Linit   Temp  Lambda
100000     1000     100    .true.   4   1.0d0
Deltax   Box    
 5      15
Alpha   Rcut
1.0d0   2.0d0
endofdata1

time ../Source/a.out